name: doubble_demo
description: A new Flutter Demo.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  provider: ^6.0.0
  graphql_flutter: ^5.1.2
  hooks_riverpod: ^2.3.6
  riverpod: ^2.3.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  
